# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tlion', '0004_auto_20170421_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(auto_now=True, verbose_name='评论发表时间')),
                ('content', models.TextField(default='no comment', verbose_name='评论内容')),
                ('name', models.CharField(max_length=10, verbose_name='评论者名字')),
                ('email', models.EmailField(max_length=255, verbose_name='评论者邮箱')),
                ('url', models.EmailField(blank=True, max_length=255, null=True, verbose_name='评论者网址')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlion.Article', verbose_name='评论所属文章')),
            ],
        ),
    ]
