# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='评论者网址'),
        ),
    ]
