# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20170421_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment', verbose_name='评论回复'),
        ),
        migrations.AddField(
            model_name='comment',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
