# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20170424_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
