# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_comment_comments_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments_num',
        ),
    ]
