# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlion', '0002_auto_20170421_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='评论者网址'),
        ),
    ]
