# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlion', '0005_article_comments_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments_num',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='评论数'),
        ),
    ]
