# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlion', '0006_auto_20170422_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments_num',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
    ]
