# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlion', '0007_auto_20170422_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments_num',
        ),
    ]
