# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlion', '0011_auto_20170424_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(blank=True, default='static/img/1.jpg', upload_to='uploads/'),
        ),
    ]
